### ISSUE TITLE
This should be True. When Admin Click on those button a popup should appear

### ISSUE THREAD

**Issue by shuvankarsa** [ponickkhan/DynamicProduct#1]
https://github.com/ponickkhan/DynamicProduct/blob/cd2335a91358e3ebf83758ba99c4568fd37a5c2d/view/adminhtml/templates/system/config/create.phtml#L12

**Comment by ponickkhan** [comment]
sorry vai i did not notice you have created an issue , as its already late working hour. but if you allow i  might be able to look into it tomorrow early morning and make necessary adjustment

**Comment by ponickkhan** [comment]
i have updated the value to true now , thanks for the improvement
